import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["vitest"],
  overrides: [
    {
      files: ["**/*.{test,spec}.{ts,tsx,js,jsx}", "**/__tests__/**/*.{ts,tsx,js,jsx}"],
      jsPlugins: [
        {
          name: "vitest-js",
          specifier: "@veyorhq/oxlint/plugins/vitest",
        },
        {
          name: "test-format",
          specifier: "@vitest/eslint-plugin",
        },
      ],
      rules: {
        "eslint/max-lines-per-function": "off",
        "max-nested-callbacks": "off",
        "no-empty-function": "off",
        "test-format/padding-around-all": "error",
        "vitest-js/no-ambiguous-called-with": "error",
        "vitest-js/no-assertion-in-callback": "error",
        "vitest-js/no-boolean-expect": "error",
        "vitest-js/no-callback-capture": "error",
        "vitest-js/no-control-flow": "error",
        "vitest-js/no-finally": "error",
        "vitest-js/no-global-mock-cleanup": "error",
        "vitest-js/no-indirect-msw-overrides": "error",
        "vitest-js/no-inexact-cardinality": "error",
        "vitest-js/no-inline-msw-url": "error",
        "vitest-js/no-internal-module-mock": "error",
        "vitest-js/no-mock-calls": "error",
        "vitest-js/no-mock-implementation-shortcut": "error",
        "vitest-js/no-promise-constructor": "error",
        "vitest-js/no-test-timers": "error",
        "vitest-js/no-test-yield": "error",
        "vitest/consistent-test-it": "error",
        "vitest/consistent-vitest-vi": "error",
        "vitest/expect-expect": "error",
        "vitest/hoisted-apis-on-top": "error",
        "vitest/no-alias-methods": "error",
        "vitest/no-commented-out-tests": "error",
        "vitest/no-conditional-expect": "error",
        "vitest/no-conditional-tests": "error",
        "vitest/no-disabled-tests": "error",
        "vitest/no-duplicate-hooks": "error",
        "vitest/no-focused-tests": "error",
        "vitest/no-identical-title": "error",
        "vitest/no-import-node-test": "error",
        "vitest/no-interpolation-in-snapshots": "error",
        "vitest/no-mocks-import": "error",
        "vitest/no-restricted-matchers": [
          "error",
          {
            toBeFalsy: "Assert the exact value",
            toBeTruthy: "Assert the exact value",
            toHaveBeenCalled: "Assert the exact call count",
          },
        ],
        "vitest/no-restricted-vi-methods": [
          "error",
          {
            waitFor: "Make the test deterministic instead",
          },
        ],
        "vitest/no-standalone-expect": "off",
        "vitest/no-test-prefixes": "error",
        "vitest/no-test-return-statement": "error",
        "vitest/no-unneeded-async-expect-function": "error",
        "vitest/prefer-called-exactly-once-with": "error",
        "vitest/prefer-called-times": "error",
        "vitest/prefer-comparison-matcher": "error",
        "vitest/prefer-each": "error",
        "vitest/prefer-equality-matcher": "error",
        "vitest/prefer-expect-resolves": "error",
        "vitest/prefer-expect-type-of": "error",
        "vitest/prefer-hooks-in-order": "error",
        "vitest/prefer-hooks-on-top": "error",
        "vitest/prefer-importing-vitest-globals": "error",
        "vitest/prefer-mock-promise-shorthand": "error",
        "vitest/prefer-mock-return-shorthand": "error",
        "vitest/prefer-snapshot-hint": "error",
        "vitest/prefer-spy-on": "error",
        "vitest/prefer-strict-boolean-matchers": "error",
        "vitest/prefer-strict-equal": "error",
        "vitest/prefer-to-be": "error",
        "vitest/prefer-to-be-object": "error",
        "vitest/prefer-to-contain": "error",
        "vitest/prefer-to-have-length": "error",
        "vitest/require-awaited-expect-poll": "error",
        "vitest/require-local-test-context-for-concurrent-snapshots": "error",
        "vitest/require-mock-type-parameters": "off",
        "vitest/require-to-throw-message": "error",
        "vitest/valid-describe-callback": "error",
        "vitest/valid-expect": "error",
        "vitest/valid-expect-in-promise": "error",
        "vitest/valid-title": "error",
        "vitest/warn-todo": "error",
      },
    },
  ],
});
